name: restock
description: "Flutter Restock app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4
  expandable_text: ^2.3.0 
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  

flutter:
  uses-material-design: true